project: TheForestNetwork.xcodeproj
schemes:
- ForestNetwork
- UnitTests
- PreviewTests
- UITests
- IntegrationTests
targets:
- ForestNetwork
- NSE
- ShareExtension
- UnitTests
- PreviewTests
- UITests
- IntegrationTests
report_exclude:
  - ForestNetwork/Sources/Mocks/Generated/GeneratedMocks.swift
  - ForestNetwork/Sources/Mocks/Generated/SDKGeneratedMocks.swift
retain_swift_ui_previews: true
