settings:
  APP_DISPLAY_NAME: The Forest Network
  PRODUCTION_APP_NAME: The Forest Network
  APP_GROUP_IDENTIFIER: group.earth.theforestnetwork
  BASE_BUNDLE_IDENTIFIER: earth.theforestnetwork.ios
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 6NYJU44FZ6

  # Optional configuration to load accounts from Element Classic.
  CLASSIC_APP_GROUP_IDENTIFIER: group.im.vector
  CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER: im.vector.app.encryption-manager-service
  CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER: "$(DEVELOPMENT_TEAM).im.vector.app.keychain.shared"
  CLASSIC_APP_DEEP_LINK_URL: "element://open"
